version: "2.0"
services:
  configservice_migrate:
    image: localhost:5000/configservice_migrate
    container_name: configservice_migrate
    extra_hosts:
      - "SQL02:172.16.10.31"
    network_mode: bridge
    restart: no
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker