version: "2.0"
services:
  configservice_migrate:
    image: localhost:5000/configservice_migrate
    container_name: configservice_migrate
    extra_hosts:
      - "SQL02:172.16.10.31"
    network_mode: bridge
  configservice_projection:
    image: localhost:5000/configservice_projection
    container_name: configservice_projection
    external_links:
      - eventstore
      - websocketservice
    extra_hosts:
      - "SQL02:172.16.10.31"
    volumes: 
      - C:/docker/logs/ConfigService/Projection:/app/logs
    restart: always
    network_mode: bridge
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
  configservice:
    image: localhost:5000/configservice
    container_name: configservice
    external_links:
      - eventstore
      - websocketservice
      - redis
    extra_hosts:
      - "SQL02:172.16.10.31"
    ports:
      - "8082:8082"
    network_mode: bridge
    volumes: 
      - C:/docker/logs/ConfigService:/app/logs
      - D:/TFS/Certs/wildcard/:/root/certs/ssl
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://*:8082
      # - ASPNETCORE_SSLCERT_PATH=/root/certs/ssl/cert.crt
      # - ASPNETCORE_SSL_PORT=8082
      # - VIRTUAL_HOST=configservice.localhost
      # - VIRTUAL_PORT=8082
 