dependencies:
  - name: websocket
    version: ^0.1.1
    condition: websocket.enabled
    repository:  https://maverick.azurecr.io/helm/v1/repo
  - name: rabbitmq
    version: ^0.1.1
    condition: rabbitmq.enabled
    repository:  https://maverick.azurecr.io/helm/v1/repo
  - name: redis
    version: 10.3.1
    condition: redis.enabled
    # import-values: 
    # - redis 
    repository:  "https://kubernetes-charts.storage.googleapis.com/"
  - name: eventstore
    version: 0.2.5
    condition: eventstore.enabled
    repository:  "https://eventstore.github.io/EventStore.Charts"