//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ConfigReferenceParser.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="ConfigReferenceParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface IConfigReferenceParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="ConfigReferenceParser.input"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInput([NotNull] ConfigReferenceParser.InputContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ConfigReferenceParser.fluff"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFluff([NotNull] ConfigReferenceParser.FluffContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ConfigReferenceParser.reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReference([NotNull] ConfigReferenceParser.ReferenceContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FullRecursive</c>
	/// labeled alternative in <see cref="ConfigReferenceParser.reference_internals"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFullRecursive([NotNull] ConfigReferenceParser.FullRecursiveContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FullReference</c>
	/// labeled alternative in <see cref="ConfigReferenceParser.reference_internals"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFullReference([NotNull] ConfigReferenceParser.FullReferenceContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ValueRecursive</c>
	/// labeled alternative in <see cref="ConfigReferenceParser.reference_internals"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValueRecursive([NotNull] ConfigReferenceParser.ValueRecursiveContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ValueReference</c>
	/// labeled alternative in <see cref="ConfigReferenceParser.reference_internals"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValueReference([NotNull] ConfigReferenceParser.ValueReferenceContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>CommandRecursive</c>
	/// labeled alternative in <see cref="ConfigReferenceParser.reference_internals"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommandRecursive([NotNull] ConfigReferenceParser.CommandRecursiveContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>CommandReference</c>
	/// labeled alternative in <see cref="ConfigReferenceParser.reference_internals"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommandReference([NotNull] ConfigReferenceParser.CommandReferenceContext context);
}
