apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "app.fullname" . }}-init
  labels: {{ include "app.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: init
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade 
    "helm.sh/hook-weight": "6"
    "helm.sh/hook-delete-policy": hook-succeeded
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  template:
    metadata:
      labels: {{ include "app.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: init
        {{- if .Values.commonLabels }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 8 }}
        {{- end }}
    spec:
      {{- include "config.imagePullSecrets" . | nindent 6 }}
      containers:
      - image: {{ include "cli.image" . }}
        imagePullPolicy: {{ .Values.cliImage.pullPolicy | quote }}
        name: {{ include "app.fullname" . }}-init
        command: ["/bin/bash", "-c"]
        args: ["tar -zxvf config/config.tar.gz && dotnet Bechtle.A365.ConfigService.Cli.dll import -s http://{{ .Chart.Name }} -f export_presales.json -f config/config-overwrite.json"]
        volumeMounts:
        - name: config-env
          mountPath: /app/config
      initContainers:
      - name: {{ include "app.fullname" . }}-init-init
        image: {{ include "curl.image" . }}
        imagePullPolicy: {{ .Values.curlImage.pullPolicy | quote }}
        command: ['sh', '-c', 'until curl http://{{ .Chart.Name }}; do echo waiting for configservice; sleep 5; done;']
      volumes:
        - name: config-env
          configMap:
            name: configservice-environment
            items:
            - key: config
              path: config.tar.gz
            - key: config-overwrite
              path: config-overwrite.json
      restartPolicy: OnFailure
status: {}