  
{{- if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: {{ template "config.networkPolicy.apiVersion" . }}
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "config.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels: {{ include "config.labels.matchLabels" . | nindent 6 }}
  ingress:
    # Allow inbound connections
    - ports:
        - port: 80
      {{- if not .Values.networkPolicy.allowExternal }}
      from:
        - podSelector:
            matchLabels:
              {{ template "common.names.fullname" . }}-client: "true"
        - podSelector:
            matchLabels: {{- include "config.labels.matchLabels" . | nindent 14 }}
      {{- end }}
    # Allow prometheus scrapes
    - ports:
        - port: 9187
{{- end }}