{{- if .Values.app.pdb.create }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "app.fullname" . }}
  labels: {{- include "app.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: service
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.app.pdb.minAvailable }}
  minAvailable: {{ .Values.app.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.app.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.app.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels: {{- include "app.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: service
{{- end }}