apiVersion: v1
kind: Service
metadata:
  {{- with .Values.service.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{ include "Config.labels" . | nindent 4 }}
  name: {{ include "Config.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  {{- with .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{ end }}
  selector: {{ include "Config.selectorLabelsService" . | nindent 4 }}
