// <auto-generated />
using System;
using Bechtle.A365.ConfigService.Common.DbObjects;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Bechtle.A365.ConfigService.Migrations
{
    [DbContext(typeof(ProjectionStoreContext))]
    [Migration("20190718140113_AddProjectionMetadata")]
    partial class AddProjectionMetadata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Bechtle.A365.ConfigService.Common.DbObjects.ConfigEnvironment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Category");

                    b.Property<bool>("DefaultEnvironment");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("ConfigEnvironments");
                });

            modelBuilder.Entity("Bechtle.A365.ConfigService.Common.DbObjects.ConfigEnvironmentKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ConfigEnvironmentId");

                    b.Property<string>("Description");

                    b.Property<string>("Key");

                    b.Property<string>("Type");

                    b.Property<string>("Value");

                    b.Property<long>("Version");

                    b.HasKey("Id");

                    b.HasIndex("ConfigEnvironmentId");

                    b.ToTable("ConfigEnvironmentKey");
                });

            modelBuilder.Entity("Bechtle.A365.ConfigService.Common.DbObjects.ConfigEnvironmentKeyPath", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ConfigEnvironmentId");

                    b.Property<string>("FullPath");

                    b.Property<Guid?>("ParentId");

                    b.Property<string>("Path");

                    b.HasKey("Id");

                    b.HasIndex("ConfigEnvironmentId");

                    b.HasIndex("ParentId");

                    b.ToTable("AutoCompletePaths");
                });

            modelBuilder.Entity("Bechtle.A365.ConfigService.Common.DbObjects.ProjectedConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ConfigEnvironmentId");

                    b.Property<string>("ConfigurationJson");

                    b.Property<Guid>("StructureId");

                    b.Property<int>("StructureVersion");

                    b.Property<bool>("UpToDate");

                    b.Property<DateTime?>("ValidFrom");

                    b.Property<DateTime?>("ValidTo");

                    b.Property<long>("Version");

                    b.HasKey("Id");

                    b.HasIndex("ConfigEnvironmentId");

                    b.HasIndex("StructureId");

                    b.ToTable("ProjectedConfigurations");
                });

            modelBuilder.Entity("Bechtle.A365.ConfigService.Common.DbObjects.ProjectedConfigurationKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Key");

                    b.Property<Guid>("ProjectedConfigurationId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("ProjectedConfigurationId");

                    b.ToTable("ProjectedConfigurationKey");
                });

            modelBuilder.Entity("Bechtle.A365.ConfigService.Common.DbObjects.ProjectedEventMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("Changes");

                    b.Property<DateTime>("End");

                    b.Property<long>("Index");

                    b.Property<bool>("ProjectedSuccessfully");

                    b.Property<DateTime>("Start");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("ProjectedEventMetadata");
                });

            modelBuilder.Entity("Bechtle.A365.ConfigService.Common.DbObjects.ProjectionMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("LastActiveConfigurationId");

                    b.Property<long?>("LatestEvent");

                    b.HasKey("Id");

                    b.ToTable("Metadata");
                });

            modelBuilder.Entity("Bechtle.A365.ConfigService.Common.DbObjects.Structure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.ToTable("Structures");
                });

            modelBuilder.Entity("Bechtle.A365.ConfigService.Common.DbObjects.StructureKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Key");

                    b.Property<Guid>("StructureId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("StructureId");

                    b.ToTable("StructureKey");
                });

            modelBuilder.Entity("Bechtle.A365.ConfigService.Common.DbObjects.StructureVariable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Key");

                    b.Property<Guid>("StructureId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("StructureId");

                    b.ToTable("StructureVariable");
                });

            modelBuilder.Entity("Bechtle.A365.ConfigService.Common.DbObjects.UsedConfigurationKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Key");

                    b.Property<Guid>("ProjectedConfigurationId");

                    b.HasKey("Id");

                    b.HasIndex("ProjectedConfigurationId");

                    b.ToTable("UsedConfigurationKey");
                });

            modelBuilder.Entity("Bechtle.A365.ConfigService.Common.DbObjects.ConfigEnvironmentKey", b =>
                {
                    b.HasOne("Bechtle.A365.ConfigService.Common.DbObjects.ConfigEnvironment", "ConfigEnvironment")
                        .WithMany("Keys")
                        .HasForeignKey("ConfigEnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Bechtle.A365.ConfigService.Common.DbObjects.ConfigEnvironmentKeyPath", b =>
                {
                    b.HasOne("Bechtle.A365.ConfigService.Common.DbObjects.ConfigEnvironment", "ConfigEnvironment")
                        .WithMany()
                        .HasForeignKey("ConfigEnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bechtle.A365.ConfigService.Common.DbObjects.ConfigEnvironmentKeyPath", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("Bechtle.A365.ConfigService.Common.DbObjects.ProjectedConfiguration", b =>
                {
                    b.HasOne("Bechtle.A365.ConfigService.Common.DbObjects.ConfigEnvironment", "ConfigEnvironment")
                        .WithMany()
                        .HasForeignKey("ConfigEnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bechtle.A365.ConfigService.Common.DbObjects.Structure", "Structure")
                        .WithMany()
                        .HasForeignKey("StructureId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Bechtle.A365.ConfigService.Common.DbObjects.ProjectedConfigurationKey", b =>
                {
                    b.HasOne("Bechtle.A365.ConfigService.Common.DbObjects.ProjectedConfiguration", "ProjectedConfiguration")
                        .WithMany("Keys")
                        .HasForeignKey("ProjectedConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Bechtle.A365.ConfigService.Common.DbObjects.StructureKey", b =>
                {
                    b.HasOne("Bechtle.A365.ConfigService.Common.DbObjects.Structure", "Structure")
                        .WithMany("Keys")
                        .HasForeignKey("StructureId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Bechtle.A365.ConfigService.Common.DbObjects.StructureVariable", b =>
                {
                    b.HasOne("Bechtle.A365.ConfigService.Common.DbObjects.Structure", "Structure")
                        .WithMany("Variables")
                        .HasForeignKey("StructureId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Bechtle.A365.ConfigService.Common.DbObjects.UsedConfigurationKey", b =>
                {
                    b.HasOne("Bechtle.A365.ConfigService.Common.DbObjects.ProjectedConfiguration", "ProjectedConfiguration")
                        .WithMany("UsedConfigurationKeys")
                        .HasForeignKey("ProjectedConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
